services:

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    deploy:
      mode: global

    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  prometheus:
    image: prom/prometheus:main-distroless

    command:
      - '--config.file=/prometheus.yaml'

    configs:
      - source: prometheus_config
        target: '/prometheus.yaml'

    ports:
      - '9090:9090'

  grafana:

    image: grafana/grafana:main-ubuntu
    deploy:
      mode: global

configs:
  prometheus_config:
    file: 'prometheus.yaml'
